version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://postgres:password@db/grids_cms_development
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/grids-cms